### ISSUE TITLE
Amend citation 

### ISSUE THREAD

**Issue by tracychew** [seek4science/seek#1160]
There are a few issues with how citations appear in workflowhub. I'd like to suggest using Github's CITATION.cff file to populate the citation box in WorkflowHub. This would resolve these issues including: 

- Authors do not appear in the order specified in Manage Workflow 
- Not all authors appear, despite being listed as creators. 
- We would like to include authors who do not have a workflowhub account
- It is missing a few fields required by some citation styles, including version of the workflow and date released

Using CITATION.cff would also ensure consistency between the two platforms. 

Here's an example: https://workflowhub.eu/workflows/146

**Comment by fbacall** [comment]
Thanks for reporting this.

The citation in that box is generated from the metadata registered with the DOI provider that was submitted when the DOI was minted. Was the list of authors edited after the DOI was generated? Currently metadata is not synchronized, and you would have to create a new version of the workflow in WorkflowHub and mint another DOI to refresh this.

We have an open issue relating to CFF support #682 but I think ideally the metadata held by the DOI provider should be accurate, because other software/services may also generate citations based on that metadata.

**Comment by LANajeraC** [comment]
Has any other solution been implemented to fix the citation issues? In my case, the last author is not appearing in the citation box,  for some reason got deteletd when minting the DOI, and I add it after that.
