### ISSUE TITLE
 Omniauth + AzureAD

### ISSUE THREAD

**Issue by jwloubser** [seek4science/seek#1446]
This request is to implement AzureAD auth with Seek to allow AzureAD 2FA functions.
Allow easy Gui base config with AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID
This will include flow/redirect based SSO to AzureAD portal

The decision was made to use Seek for research data storage.
One of the requirement will be to have AzureAD with 2FA.
I have seen sample configs for Omniauth + oauth2 module.
Is this possible and how would i go about to do the configuration.

config.omniauth :azure_oauth2, client_id: ENV['AZURE_CLIENT_ID'], client_secret: ENV['AZURE_CLIENT_SECRET'], tenant_id: ENV['AZURE_TENANT_ID']

**Comment by stuzart** [comment]
this could be looked at in conjuction with #1030 and I think would be very similar to the github authentication settings

**Comment by fbacall** [comment]
I think this should now be possible using the "OpenID Connect authentication" authentication option under Admin > Enable/disable features

From here: https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri
it sounds like you can use `https://login.microsoftonline.com/{tenant}/v2.0`  as the "OpenID Connect URL"

If this is not the case, please re-open

**Comment by simklei** [comment]
I was able to implement authentication using OpenID Connect with Microsoft Entra (previously Azure AD) as identity provider, but it needed a minor, non-backwards compatible, modification of the code.

As a prerequisite, I obtained the Client ID and Client Secret by creating an [App Registration](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=client-secret), where the redirect URI and grant type could be submitted.

The required modification is due to the `issuer` value that is returned by Microsoft OpenID Connect configurations lacks a trailing "/". This can be seen in `issuer` field at the ["common" OIDC configuration](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration). In SEEK, a "/" is automatically appended to the `omniauth_oidc_issuer`, see [app/controllers/admin_controller.rb (line 103)](https://github.com/seek4science/seek/blob/c2dffbbb823440994057f99aa97540dabfde71ea/app/controllers/admin_controller.rb#L103). This showed up in the logs with the following error message: `(oidc) Authentication failure! Issuer mismatch: OpenIDConnect::Discovery::DiscoveryFailed, Issuer mismatch`.

With inspiration from the "LS Login authentication" > "Use legacy configuration" setup, I fixed this for my instance by adding a `omniauth_oidc_microsoft_mode` under `omniauth_oidc_config` ([lib/seek/config.rb (line 400)](https://github.com/seek4science/seek/blob/f3b365c4b47e4303a5c456111b55851686090b17/lib/seek/config.rb#L400)), where the issuer field is set using `issuer: omniauth_oidc_issuer.chomp('/')`. This mode is activated with a new "Use Microsoft Configuration" Boolean setting under "OpenID Connect authentication". In hindsight, since the trailing "/" was the only modification that was needed, a more generic "Add trailing backslash to issuer" that defaults to `true` might be a smoother way to solve this issue while keeping backwards-compatibility.

On a related note, the Microsoft "common" OIDC configuration is not strictly compliant with OIDC specifications, since the `issuer` field contains a placeholder `{tenantid}` value, that does not match the `iss` field that is eventually returned, where `{tenantid}` has been resolved to an actual tenant id. See https://github.com/MicrosoftDocs/azure-docs/issues/38427. My use case is for a single organization/tenant, so I was not affected by this.
