### ISSUE TITLE
Change workflow type "PyCOMPSs" to "COMPSs"

### ISSUE THREAD

**Issue by rsirvent** [seek4science/seek#1464]
Hi there. Could you change the name and details listed for "PyCOMPSs" workflow type? As in:

https://workflowhub.eu/workflow_classes

- Name should be "COMPSs" (PyCOMPSs refers specifically to the COMPSs Python binding).
- Identifier and URL should be: "https://compss.bsc.es/"

Thanks!

**Comment by rsirvent** [comment]
I see the website is used to detect the "workflow type", then the correct link should be: http://compss.bsc.es/

**Comment by fbacall** [comment]
It makes a few attemps to match the workflow type:

1. The `@id` of the main workflow's `ComputerLanguage` is matched against the `identifier` of the workflow types in WorkflowHub.
2. Then tries to match on the `name`/`alternateName`.
3. If the `@id` is an internal identifier (e.g. `#compss`), it will try and match it on the `key` of the workflow type (an internal identifier that WorkflowHub uses for filtering).
4. Lastly, it tries to match on the `url`.

So in your RO-Crate metadata you could opt to use `http://compss.bsc.es/` as the `@id` of the `ComputerLanguage`, and then point to something else as the `url` (although in this case I think it's fine as it is since your identifier also directs to a website with information about the type).
