### ISSUE TITLE
Sample attribute types still mistakenly includes Ontology

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1632]
Ontology just duplicates Controlled Vocabulary

**Comment by floradanna** [comment]
what could be a quick fix for that?

does it relate to #802 ?

**Comment by stuzart** [comment]
I've just been looking at it. I will need to find all sample_attributes associated with the Ontology attribute type, and moved them to the "Controlled Vocabularly" attribute type, and then delete the Ontology one.

I'm not sure #802 is relevant any more. A different flag is now used to determine whether a CV can accept new terms, regardless of whether it was populated from an ontology or not. ( `.custom_input?` ). It's set on the CV, but we have discussed that it would be better on the sample attribute as it depends on how the CV is used

**Comment by floradanna** [comment]
does it mean that the attribute type Ontology will not exist anymore?

@kdp-cloud we use attribute type = ontology in our json templates. Will this change affect the templates? 
Initially, we made the DT so that
- attribute type = CV --> accept only terms from the list
- attribute type = ontology --> ontology terms are suggested, but user can type any free text
I think this behaviour is already compromised in the DT.
Shall we address this issue step-by-step and work on short-term and long-term solution?
@stuzart please, let us know what you think.

About `.custom_input?`, I think I would need more information, but we would want to avoid:
- that CV List get edited by end-users at any moment
- confusion between attributes that enforce CV List and attributes that don't without any clear distinction or reason

**Comment by stuzart** [comment]
Both Controlled Vocabularly and Ontology attribute types are exactly the same, and are defined the same.
There was only ever a hard-coded hack that marked some controlled vocabs as allowing free text based on an ontology flag in the html markup, but I don't think this was set according to the attribute type. It led to some bugs and therefore was changed to use an explicit `.custom_input` regardless of where the CV came from.

As you can see here, both Controlled Vocab and Ontology have the same definition and base type, just a different title:
CV - https://github.com/seek4science/seek/blob/main/db/seeds/007_sample_attribute_types.seeds.rb#L67-L68
Ontology - https://github.com/seek4science/seek/blob/main/db/seeds/007_sample_attribute_types.seeds.rb#L82-L83

both take you to the same pages and have the same behaviour.

The Ontology attribute type is causing confusion. We don't support ontologies, but only support populating a Controlled Vocab with terms derived from an Ontology (there using a subset of an ontology as a CV, but not any other ontology properties)
