### ISSUE TITLE
Faceted search - 2 times "Germany" if searching for events

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#194]
Search events gives a list of events and country facet  shows 2 line with " Germany" with different number per line /screenshot attached)
![FacettedSearch_2Germanies](https://user-images.githubusercontent.com/55085007/77766491-01e19400-7040-11ea-966e-c8c16b74e998.jpg)

**Comment by OlgaKrebs** [comment]
United Kindom also appears twice - not together but with diff numbers as well

**Comment by stuzart** [comment]
It seems to orginate from an inconsistency between how country codes are stored, sometimes the code (ie DE), and full name (Germany). In the view they are both translated to full form.
This should have been fixed in 1.9 but we think we've found a problem in the upgrade task, which can be easily be fixed ane rerun

**Comment by fbacall** [comment]
This is fixed, but there is a mystery "blank" country:
![image](https://user-images.githubusercontent.com/503373/77770587-664f2400-703d-11ea-954a-7ad8be8d8e3d.png)
