### ISSUE TITLE
Publications: Only year is imported

### ISSUE THREAD

**Issue by InaSchmitt** [seek4science/seek#1952]
For some publications only the year of Publication is imported into the field "Date Published" 
E.g. https://seek.lisym.org/publications/424

**Comment by stuzart** [comment]
I think this appears to be because that is the only info we get back for the doi metdata when querying crossref. I've checked the xml we get back for the publication you link to, and all I can find is:

```
<publication_date media_type="print">
    <year>2024</year>
</publication_date>
```

for both the journal and the article. I can't find any other possible dates in the XML response

**Comment by stuzart** [comment]
... another example, that we get for https://seek.lisym.org/publications/431 gives fuller information:

```
<publication_date media_type="online">
  <month>05</month>
  <day>04</day>
  <year>2024</year>
</publication_date>
```

**Comment by InaSchmitt** [comment]
I see. Then I guess it's on the Journal site and has to be accepted. Thanks for checking!
