### ISSUE TITLE
Sample links to registered files are not displaying the the Datafile samples table view

### ISSUE THREAD

**Issue by AndrewWood94** [seek4science/seek#2052]
When extracting Samples which include a 'Registered Data File' attribute, the link to the associated datafile works when viewing the confirm extraction table ([e.g. column 'ImageFile' here](https://testing-suburi.fairdomseek.org/seek/data_files/5/confirm_extraction)). 

However, once the file has been extracted, the Datafile samples table displays [object Object] instead of the linked datafile
([example here](https://testing-suburi.fairdomseek.org/seek/data_files/4/samples?graph_view=tree))

**Comment by stuzart** [comment]
thanks @AndrewWood94 . I think this a UI issue and case of it not being updated as the features have evolved.

The button to view samples was originally added just to show extracted samples, before there was the ability to link data files through a sample attribute. Since this was added, the `related_samples` has been updated, and does include the linked samples as well as the extracted ones, but clicking the link to view all takes you to `data_files/n/samples` which just displays the extracted ones.

I think it needs updating so that the button is clearer that it is to show only the extracted samples, with its own route, but then `data_files/n/samples` should show the usual filtered view and include all related samples.

**Comment by AndrewWood94** [comment]
Is it possible to have samples related to a datafile which are not extracted from the datafile?
If not, I think it would be good for the ISA graph to link to extracted samples rather than related samples, so users can see the sample data, not just metadata

**Comment by stuzart** [comment]
yes, it is possible to have other samples related to a data file. Those that have been linked through the Registered DataFile sample attribute. So, data_file.related_samples can contain a mixture of those extracted and others that are linked through this attribute.

**Comment by stuzart** [comment]
As mentioned on wednesday, fixing this raised some other issues so there is an issue for future improvements #2057 . But closing this as the underlying problem reported has been fixed.
