### ISSUE TITLE
seek 1.1.1 tries to explore 'csv' files, and fails 

### ISSUE THREAD

**Issue by fbergmann** [seek4science/seek#21]
Hello, 

when uploading a CSV file to seek 1.1.1 the explore button is enabled. However, this results in a crash (500 error) as the simple extractor cannot deal with csv files. The view option on the other hand is disabled even thought the tooltip says that csv files should be displayable. 

Ideally csv and tsv files could both be explored, it would be easy enough to have those files be converted to spreadsheets.

cheers
Frank

**Comment by stuzart** [comment]
Thanks Frank for pointing this out. I will have a look into.

**Comment by stuzart** [comment]
I've been looking into this, but can't seem to reproduce it. I do not get the Explore button for a csv file, and for 1.1.1 the view button worked correctly. I did come across a fix required due to some later changes (hence the earlier commit), but I don't think this would have affected 1.1.1

Could you check that when showing the csv file you get the information "Format: Comma-separated values document" - for example like: https://testing.sysmo-db.org/data_files/167

**Comment by stuzart** [comment]
( I've also added an issue to our JIRA for your suggestion of Exploring csv files via a conversion - https://jira-bsse.ethz.ch/browse/OPSK-890 )
