### ISSUE TITLE
ISA Compatibility

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#477]
SEEK's ISA model and the ISATab/JSON formats are not quite compatible. 

We should think about how to align them so we could make use of the various ISA tools to assist with converting between formats and exporting to repositories.

**Comment by floradanna** [comment]
Regarding the question, I would need a clarification about the type of metadata we are discussing.

1. I assume you are refering strictly to any Object and Attribute defined by the ISA specifications and formalized in the ISA JSON schema 1.0 ?

So I understand your question as: for the Study Object, which are the fields which should be minimally supplied?

If that's the case, then for most objects, the required information is Name and Identifier (if not autogenerated by the API). 

For specific objects such as ISA.Protocol, ISA.Factor, ISA.Assay , the associated 'types' must be provided. so `ISA.Protocol.type` and `ISA.StudyFactor.type`

For ISA.Assay, `ISA.Assay.measurement_type` must be provided, and `ISA.Assay.technology_type` is strongly recommended but not mandatory.

2. If "metadata" refers to descriptors outside the ISA syntax 

I am talking about things such as 'Disease', 'Instrument Temperature', 'Organism Part', then one may define ISA.Configurations/metadata profiles but such requirements are not to be found in the ISA schema itself

Let me know if this helps and if more information is needed.

Also, let me know about any mapping FAIRDOM-SEEK is making so I can review it and possibly advise.

**Comment by floradanna** [comment]
Additional info about ISA.
- The documentation is  available from the ISA-Tab specifications: https://isa-specs.readthedocs.io/en/latest/isatab.html. Alternately, in what from, we would want to have this information?

- Descriptors outside ISA syntax are configurable, and could be defined based on metadata elements require by a EBI repository (for instance, ENA), but only to some extend. If you want to use some of the ISA conversion functions, you'd need to use the configurations we have defined and support for the deposition paths. If you choose to develop / redevelop the code, please do let the us (the ISA Team) known so we make sure we don't have incompatible implementation of the same checklists.

**Comment by floradanna** [comment]
@proccaserra
1) can 2 assays in the same study have 2 different measurement type?
2) must the number of "sample entries" be the same of "source entries"? Or the number of "sample entries" in an assay can be bigger or smaller than the number of "source entries" in the study?

**Comment by proccaserra** [comment]
@floradanna 
1. Yes, absolutely. this is why ISA was designed in the first place, to allow multi-omics, multi-modality data acquisition studies to be reported.

STUDY ASSAYS |   |   |   |  
-- | -- | -- | -- | --
Study Assay File Name | a_non-polar_GC_negative_assay.txt | a_illumina_sequencing_assay.txt | a_oxfordnanopore_sequencing_assay.txt | a_both_combined_sequencing_assay.txt
Study Assay Measurement Type | metabolite profiling | transcription profiling | transcription profiling | transcription profiling
etc... |   |   |   |  
  |   |   |   |  
Study Assay Technology Type | mass spectrometry | nucleic acid sequencing | nucleic acid sequencing | nucleic acid sequencing


2. Source / Sample and Assays:
Any `Sample` used in an Assay table (if using ISA-Tab serialisation), *must* be declared. Failing that will cause the validator to raise an error. 

- the number of Samples  may be bigger than the number of Sources (e.g. multiple samples collected from a same Source, aliquoting in multiple subsamples, fractionation...)
- the number of Samples may be smaller than the number of Sources in the case of pooling events (5 mice pr group but hippocampus are pooled to performed some cell sorting)

Do you have situations where you have 'Samples' used for a data acquisition which have no declared Sources?

**Comment by floradanna** [comment]
When I used the ISA creator, I created a study with 2 rows in source and 4 rows as samples (2 samples from each source row); however I got error and I had to duplicate the sources in order to fill in 4 rows as well. So, I was wondering how this would work for pooled samples instead.

Also, in the assay file, can I only list a subset of the samples that are declared in the study file? For instance, 2 samples (out of 4) are used in assayA and the other 2 samples (out of 4) are used in assayB, in the same study.

**Comment by proccaserra** [comment]
@floradanna can you share the file you created + configuration you've used?

**Comment by floradanna** [comment]
I will have to re-create it because I don't always manage to save the exported tabs. I will let you know when I have it done. Thank you!

**Comment by floradanna** [comment]
@proccaserra I tested my own questions by using the ISA creator, however it is pity that I don't manage to see nor select data file to continue (image 7 of the pdf in attachment). There is also a problem with a SRA centre name that I don't know how to fix, therefore I cannot covert to ISA tab.

Anyway, I think I have the information I needed it for now. Thanks!


[ISAcreator.pdf](https://github.com/seek4science/seek/files/5781808/ISAcreator.pdf)

**Comment by floradanna** [comment]
@proccaserra Hi Philippe, I was wondering if you can have more than one "sample collection" protocol in ISA. From what I can see, it seems that there should be only ONE single "sample collection" protocol valid for all assay types in a study. Please, let me know if I am wrong. Thanks.

**Comment by proccaserra** [comment]
@floradanna yes this is the case. we are documenting this behaviour in a notebook. If this is a problem, could you document what information or what situation this becomes an issue ?

On top of my head, it can be possibly an issue when collecting different sample types from patients (blood, lung fluid, muscle biopsy) or various meta genomics samples.

a work around is to declare one or more parameters attached to the sample collection protocol which would give more flexibility.

I will get back to the other comment shortly . all the best.

**Comment by proccaserra** [comment]
@floradanna: 
1. can you share the ISA-Tab you have created with ISAcreator ?
2. Which version of ISA creator did you use and which with Configuration?
3. Image2: this is the expected  behaviour: an ISA record correspond to a the path of the graph projected in a 2d table so a 'branching' even where 1 source gives yield to 2 samples is represented by 2 rows in an ISA table. ISAcreator (java code) makes no assumptions based on the strings found in Material Nodes.
4. Image4: there seems to be a naming error for the second "Labeled Extract Name". This may sound contracdictory to my point above but only relates to the 'naming convention' you seem to have applied in the example. In the current example, the ISA parser (java & python) will assume that samples 'source1_a' and 'source2_a' are pooled into one extract named 'source1_b_extract', which is itself input to a labelling process which will generate 2 distinct labeled extracts , named respectively 'source1_b_labeled' and 'source2_b_labeled'. Is this the intent?
5. image 7: ISAcreator being no longer maintained, it could be a consequence of class deprecation in some of the libraries we relied on or settings to access folder information. Which OS are you running ISAcreator on?
Am i right assuming you are looking for fastq files for the sequencing application?
I'll be testing again on my end but like I said, ISAcreator is no longer supported as we focus on the python api.
6. Image 8: This is specific to the SRA conversion. It is (was) at the time of development a requirement to obtain a valid SRA Center Name in order to perform the conversion. This is supplied via a Comment field. Hence my question about which configuration you have been using?

hope this helps
bw
P

> @proccaserra I tested my own questions by using the ISA creator, however it is pity that I don't manage to see nor select data file to continue (image 7 of the pdf in attachment). There is also a problem with a SRA centre name that I don't know how to fix, therefore I cannot covert to ISA tab.
> 
> Anyway, I think I have the information I needed it for now. Thanks!
> 
> [ISAcreator.pdf](https://github.com/seek4science/seek/files/5781808/ISAcreator.pdf)

**Comment by floradanna** [comment]
1. I have never managed to save an ISA-TAB with ISA creator Light (ISAcreator-1.7.11) because of errors. I only managed to save it by using the MetaboLights ISA Creator (see attachment).
2. ISAcreator-1.7.11; I am sure about the configuration, I think this one "isaconfig-default_v2015-07-02".
3. OK, thank you.
4. Image4: I made a naming mistake in the second extract name (it should have been source2_b_extract, not source1_b_extract). I didn't intent to pool sources nor samples. I wanted to use source1_a and source2_a in Transcriptomic assay (image 3), and source1_b and source2_b in Metabolomic assay (image 4).
5. image 7: macOS Catalina Version 10.15.7
6. Image 8: see point 1.

[Document_archive.zip](https://github.com/seek4science/seek/files/5801323/Document_archive.zip)

@proccaserra  Thank you very much for your answers.

**Comment by floradanna** [comment]
@proccaserra 
Indeed, it could be an issue every time different sample types (blood/urine, root/leaf, cells/supernatant, tree/soil etc...) from a source (human, animal, plant, cell culture, environment etc...) need to be taken.
However, I would keep it as it is now: one single "sampling" protocol for the all study, otherwise everything could get more complicated. Also, this kind of issue can happen for every protocol, not only for sampling. For instance, you could extract RNA by Trizol for half of the samples and by Column for the other half (if extraction protocol is your experimental factor).

Therefore, I would keep it as it is. A simple solution is the the user will need to add more "characteristics" to describe samples, some of which apply to only a subset of samples and the rest of samples will have NA as value.

Please, let us know if you are going to change this in ISA anyway.

> @floradanna yes this is the case. we are documenting this behaviour in a notebook. If this is a problem, could you document what information or what situation this becomes an issue ?
> 
> On top of my head, it can be possibly an issue when collecting different sample types from patients (blood, lung fluid, muscle biopsy) or various meta genomics samples.
> 
> a work around is to declare one or more parameters attached to the sample collection protocol which would give more flexibility.
> 
> I will get back to the other comment shortly . all the best.
