### ISSUE TITLE
Issue in project creation

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#48]
Hello again,

I have a problem when I want to create a new project.

When I click on create, I have an Internal Server Error (500). 

In the production.log, I have this message:

> ERROR - NoMethodError (undefined method `set_attributes_with_sharing' for nil:NilClass)

I've observed that in the privacy sharing, I've an empty project automatically in the table.

![image](https://cloud.githubusercontent.com/assets/1289992/24545161/687a0176-1606-11e7-87d4-0d696acfc0cc.png)

Any ideas?

Cheers,
Cyril

**Comment by cmonjeau** [comment]
Hi,

I think it could be fix by adding project test in the app/views/projects/_form.erb (line 44):

`<% if @project.can_manage? and project%>`

**Comment by fbacall** [comment]
Hi Cyril, sorry for the late response, I was not recieving notifications for this repository...

I think there are two issues here. 

Firstly, there is a bug that stops project creation because "default_policy" is nil.

The second issue is that the default "default policy" for the project should have 1 row in the table for the project itself. But in the "create" form, the project does not exist yet so the row is blank.

I think the solution for now is to hide the default policy form from the create page, and then after creation we can prompt the user that they can go to the "edit" page to add a default poicy.
