### ISSUE TITLE
Sharing with institution does not work

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#481]
This has been found on sandbox7 by EOSC course participants and it is the same on FAIRDOMHub. If defining "sharing with " in e.g. creating assay process one chooses "Share with a project and/or institution" option and choose the projekt first, the "institutions" list gets "frozen", one can't open the list to choose institution any more

**Comment by OlgaKrebs** [comment]
![Share_InstitutionList_inactive](https://user-images.githubusercontent.com/55085007/101627641-ecba6300-3a1e-11eb-9672-3806cd089157.jpg)

**Comment by fbacall** [comment]
This URL and the one below are now undefined https://github.com/seek4science/seek/blob/master/app/views/sharing/_group_permission_modal.html.erb#L86

**Comment by stuzart** [comment]
I've taken a look, and that was removed along with the request_all method on the controller, because it was causing a separate error due to missing white_list method and it didn't seem to be used anymore. 
https://github.com/seek4science/seek/commit/0357288646bafd8c2708aa6dab61ce92a76554fc
I'll see what happened to white_list
