### ISSUE TITLE
Issue for project subscription and immediately email

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#61]
Hi,

it seems that for a project subscription, I do not receive immediately email after a content creation.

However, I receive a mail when a content was updated.

Do you have the same problem?

**Comment by fbacall** [comment]
Hi, yes I do. 

Also if I edit a resource soon after creation, I don't get an email.

I can see the reason in the code, but I'm not sure the best way to fix it right now.

It happens because when a new item is created, SEEK starts an asynchronous job to subscribe every user with a project subscription to that item. Unfortunately, by the time those subscriptions are added to the item, SEEK has already attempted to email the people with "immediate" subscriptions (which is nobody) about the item creation.

I will look into if its possible to process the project subscriptions synchronously.

**Comment by cmonjeau** [comment]
This looks good on v1.5.0. 

Thanks a lot,
Cyril
