### ISSUE TITLE
Proposal: create a super-admin role

### ISSUE THREAD

**Issue by cmonjeau** [seek4science/seek#63]
Hi, research team,

first of all, thank you very much for your new version which is great, especially the JSON API.

I want to use this API to extract information from my SEEK instance. I realized that an administrator can't see all the content (hidden content is not accessible). 

So have you thought about creating a new role, such as a super-administrator, or improving the administrator's power to see all the hidden content?

Thank you very much,
Cyril

**Comment by fbacall** [comment]
Hi Cyril, apologies, I didn't see this before.

In the early days of SEEK development we made a conscious decision not to allow administrators to see all content. This was because at the time, our user base was very concerned about privacy, and reluctant to share their data on a data management platform at all.

However, now there are groups such as yourselves using their own SEEK instances with differing privacy requirements, it may be useful to have such a "super-administrator" role - who can see/access everything.

We will discuss how much effort it will take and see if it is feasible.

Thanks,
Finn & SEEK team
