### ISSUE TITLE
"Add new" menu needs to take into account if things are enabled

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#817]
there is no control over whether an item appears if enabled or not. For example if `Seek::Config.events_enabled==false` then the menu item still appears to Add a new Event to Presentation

**Comment by fbacall** [comment]
I added a method `feature_enabled?`: https://github.com/seek4science/seek/blob/master/app/models/application_record.rb#L156-L159
which can be used to check if that model is enabled (returns true if there is no setting)

Also @aapaolaza 's commit should not be needed since it checks if the feature is enabled in `fancy_multiselect` now

**Comment by stuzart** [comment]
OK. I did consider adding a method like that, but didn't realise there already was one. It could be refactored to use that instead
