### ISSUE TITLE
Rename SEEK Samples, and SEEK Samples Multi attribute types

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#858]
Remove the word SEEK, which describes the platform rather than instance. Just use Registered Samples, and Registered Multiple Samples

**Comment by rabuono** [comment]
"Registered Multiple Samples" might be confusing.

Can the attribute types be named as:
`Single Registered Sample`
`Multiple Registered Samples`
Or will they be positioned far from each other in the menu due to alphabetical ordering?

Otherwise, something like:
`Registered Sample`
`Registered Samples (multiple)`
