### ISSUE TITLE
Samples not showing in "Items in ISA" in "Batch permission changes"

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#907]
**Describe the bug**
In `Batch permission changes`.
When Samples are assigned to an Assay they disappear from the `Items not in ISA`, but they don't appear under their ISA asset in the `Items in ISA` menu

**To Reproduce**
1. Create a Sample
2. Go to `Batch permission changes` and find it under `Items not in ISA` 
3. Add it to an Assay
4. Go back to `Batch permission changes`. It is no longer under `Items not in ISA`, but it is also not under `Items in ISA` 

**Expected behavior**
The Samples assigned to an ISA asset should appear under that asset in the `Items in ISA`

**Comment by floradanna** [comment]
Just few comments to clarify the issue:
* samples are already included in batch sharing permission; only samples that are linked to assays disappear form batch sharing permission GUI. So this issue is about fixing an inconsistency or a bug.
* since the items are shown in a tree view, I would suggest to use the same style and graphic of the tree view already used in other pages (with dotted lines connecting little arrows etc)

**Comment by floradanna** [comment]
DataHub developed "batch sharing permission" for samples that have been:
- created via Single Page
- in a sample type that is linked to one study or to one assay

<img width="1142" alt="Screenshot 2023-08-10 at 15 25 08" src="https://github.com/seek4science/seek/assets/51486716/cc0701e1-da12-4143-b508-33279ce0734e">


However, those samples are also visible as "Items not is ISA" when clicking My profile --> batch permission changes
So, user can change permission of samples "linked" to ISA also via "Items not is ISA".

![Screenshot 2023-08-10 at 15 21 37](https://github.com/seek4science/seek/assets/51486716/bda7f48e-e15a-4d3a-bc47-b90562ae1b8e)

**Comment by floradanna** [comment]
Samples associated with ISA Assay behave inconsistency: some samples are shown as "Items not in ISA", some other samples are not shown at all. To be investigated.

**Comment by floradanna** [comment]
related to PR #1551
