### ISSUE TITLE
Additional authentication options

### ISSUE THREAD

**Issue by Linus4** [seek4science/seek#984]
As far as I can tell, the [omniauth-ldap](https://github.com/omniauth/omniauth-ldap) strategy does not support LDAP**S** using custom CA certificates which we need in order to use this service in some environments.

As an alternative, our datacenter operates a [Keycloak](https://www.keycloak.org/) instance which supports OpenID Connect, OAuth 2.0, and SAML 2.0. There are actively maintained strategies available for omniauth, so it would be really nice if SEEK would support any of those strategies.

**Comment by kiwiroy** [comment]
AFAICT OIDC is already supported since the [gem](https://github.com/seek4science/seek/blob/077e5ad794df95cf293110ba6553222bae15dd8e/Gemfile#L98) is a dependency and the Elixir AAI configured is talking OIDC
https://github.com/seek4science/seek/blob/077e5ad794df95cf293110ba6553222bae15dd8e/lib/seek/config.rb#L310-L338

Generalising the code to work with [`discovery: true`](https://github.com/omniauth/omniauth_openid_connect#additional-configuration-notes) and in the case of Elixir AAI `issuer: https://login.elixir-czech.org/oidc/` would allow for the discovery from any configuration endpoint i.e. https://login.elixir-czech.org/oidc/.well-known/openid-configuration . Further, configuring through the UI, including provider specific button image, would be a nice enhancement.
